BOT_TOKEN = ...
GPT_TOKEN = ...


provider_token = ...
user = ...
password = ...
host = "localhost"
port = 5432
database = ...
DB_CONNECTION_URL = f"postgresql+asyncpg://{user}:{password}@{host}/{database}"

